language: node_js
node_js:
  - "node"
  - "lts/*"
  - "10.14.2"

install:
  - npm ci

# as a library, we test both source and dist, and so we need to build before testing
before_script:
  - npm run build:prod

# default `script` for a `node_js` travis setup is `npm test`, which will test both
# source and dist (as explained in the project README)

# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/.npm"
